/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Andy' at '16-5-30 上午11:10' with Gradle 2.12
 *
 * @author Andy, @date 16-5-30 上午11:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
